# Generated by Django 3.1 on 2019-12-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haddock', '0003_auto_20191208_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
