# Generated by Django 3.1 on 2019-12-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haddock', '0004_auto_20191208_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolvido', models.CharField(max_length=30)),
                ('criador', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=300)),
                ('criticidade', models.IntegerField()),
            ],
        ),
    ]
