# Generated by Django 3.1 on 2019-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haddock', '0005_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='incidente',
            field=models.CharField(default='0000000', max_length=300),
        ),
    ]
