# Generated by Django 3.1 on 2019-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haddock', '0006_registro_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
    ]
